\input texinfo @c -*-texinfo-*-
@setfilename guide.info
@include version.texi
@settitle Guidelines for modern code review @value{UPDATED-MONTH}
@setchapternewpage odd

@finalout

@smallbook


@c @copying

MIT licensed.


@shorttitlepage Modern review rules.

@titlepage
@title Guidelines for modern code review
@subtitle @value{UPDATED-MONTH}
@author John Hanley

@page
@vskip 0pt plus 1filll
@c @insertcopying
@end titlepage

@ifnottex
@node Top
@top review rules

@c @insertcopying

@cindex foo
@cindex baz
@end ifnottex


@c @node Introduction
@chapter Introduction

Code quality matters.

There is one rule above all others:

Be kind to the reader.

Several rules stem from this.
@itemize @bullet
@item
DRY - don't repeat yourself.
@item
If a method has grown longer than a hundred lines, break it apart,
with helper methods.
@item
Coupling of variables is a burden upon the reader.
Definitely stop once a class has two dozen attributes - break it up.
@end itemize

@summarycontents
@contents
@bye
